//Login ACTION TYPES

export const LOGIN_AUTH_PENDING = 'LOGIN_AUTH_PENDING';
export const LOGIN_AUTH_FAILURE = 'LOGIN_AUTH_FAILURE';
export const LOGIN_AUTH_SUCCESS = 'LOGIN_AUTH_SUCCESS';
export const SIGNUP_AUTH_PENDING = 'SIGNUP_AUTH_PENDING';
export const SIGNUP_AUTH_FAILURE = 'SIGNUP_AUTH_FAILURE';
export const SIGNUP_AUTH_SUCCESS = 'SIGNUP_AUTH_SUCCESS';